# Generated by Django 5.0.4 on 2024-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polkadot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.TextField(default='Your image'),
            preserve_default=False,
        ),
    ]
