# Generated by Django 5.0.4 on 2024-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polkadot', '0002_imagemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
