# Generated by Django 5.0.4 on 2024-04-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polkadot', '0003_alter_imagemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='name',
            new_name='comments',
        ),
    ]
