# Generated by Django 5.0.4 on 2024-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polkadot', '0005_alter_imagemodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='comments',
            field=models.TextField(max_length=255),
        ),
    ]
